name: Slack Slasch Command Example

on:
  repository_dispatch:
    types:
      - slack-slash-command-example

jobs:
  demo:
    name: Run Demo
    runs-on: ubuntu-latest
    env:
      PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
      USER_NAME: ${{  github.event.client_payload.data.user_name }}

    steps:
      - name: Send Slack Message
        uses: actions/checkout@v2
      - run: |
                chmod +x ./test.sh
                 ./test.sh
        shell: bash
