name: Slack Slasch Command Example

on:
  repository_dispatch:
    types:
      - slack-slash-command-example

jobs:
  demo:
    name: Run Demo
    runs-on: ubuntu-latest
    env:
      PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
      USER_NAME: ${{  github.event.client_payload.data.user_name }}

    steps:
      - name: Send Slack Message
        uses: dkershner6/post-api-call-action@v1
        with:
         url: https://hooks.slack.com/services/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
         data: "{\"text\": \"Hello <@${{ env.USER_NAME }}> from the running GitHub Actions Workflow.\"}"
         headers: "{\"Content-type\": \"application/json\"}"
       #  params: "{\"content\": \"Test Content\"}"
    
